# lightning.pytorch==2.1.2
seed_everything: 42
data:
  train_chip_dir: /home/clebson/Documentos/dataset_palmls4claymodel/data/train/img/
  train_label_dir: /home/clebson/Documentos/dataset_palmls4claymodel/data/train/gt/
  val_chip_dir: /home/clebson/Documentos/dataset_palmls4claymodel/data/val/img/
  val_label_dir: /home/clebson/Documentos/dataset_palmls4claymodel/data/val/gt/
  metadata_path: configs/metadata.yaml
  batch_size: 8
  num_workers: 8
  platform: landsat-c2l2-sr
model:
  num_classes: 1
  ckpt_path: checkpoints/clay-v1.5.ckpt
  lr: 5e-6 #1e-5
  wd: 0.05
  b1: 0.9
  b2: 0.95
trainer:
  accelerator: auto
  strategy: ddp
  devices: auto
  num_nodes: 1
  precision: bf16-mixed
  log_every_n_steps: 5
  max_epochs: 100
  accumulate_grad_batches: 1
  default_root_dir: checkpoints/segment
  fast_dev_run: False
  num_sanity_val_steps: 0
  #logger:
  #  - class_path: lightning.pytorch.loggers.WandbLogger
  #    init_args:
  #      entity: developmentseed
  #      project: clay-segment
  #      group: v1.5
  #      log_model: false
  logger:
  - class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: logs/

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: checkpoints/segment
        auto_insert_metric_name: False
        filename: chesapeake-1class-segment-landsat_epoch-{epoch:02d}_val-iou-{val/iou:.4f}_val-loss{val/loss:.4f}
        monitor: val/iou
        mode: max
        save_last: True
        save_top_k: 2
        save_weights_only: True
        verbose: True
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
  plugins:
    - class_path: lightning.pytorch.plugins.io.AsyncCheckpointIO
